name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install github-contribution-grid-snake-cli

      - name: Generate github-contribution-grid-snake.svg
        run: npx github-contribution-grid-snake -u ${{ github.repository_owner }} -o dist/github-contribution-grid-snake.svg -g "#8A3AB9,#FF66B2"

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate github-contribution-grid-snake.svg"
          git push origin master
